# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  tomcat:
    uri-encoding: "UTF-8"

spring:

  http:
    encoding: "UTF-8"
    force: true

  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

  jpa:
    properties:
      useEncoding: true
      characterEncoding: "UTF-8"
    show-sql: true

  messages:
    basename: "messages"
    cacheSeconds: -1
    encoding: "UTF-8"
